export const Types = {

    //signUp
    TOGGLE_CREATE_ACCOUNT_ACTION_LOADER:"TOGGLE_CREATE_ACCOUNT_ACTION_LOADER",
    CREATE_ACCOUNT_SUCCESS:"CREATE_ACCOUNT_SUCCESS",
    RESET_CREATE_ACCOUNT:"RESET_CREATE_ACCOUNT",

    //signIn
    TOGGLE_AUTH_LOADER:"TOGGLE_AUTH_LOADER",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    SAVE_API_TOKEN:"SAVE_API_TOKEN",
    RESET_AUTH_STATE:"RESET_AUTH_STATE",
    REST_LOADER:"REST_LOADER",


    //dashboard
    SAVE_DASHBOARD_LIST:"SAVE_DASHBOARD_LIST",
    TOGGLE_DASHBOARD_ACTION_LOADER:"TOGGLE_DASHBOARD_ACTION_LOADER",
}
